apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  containers:
  - image: project-1:latest
    name: app
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "1"
        memory: "52428800"
      requests:
        cpu: "1"
        memory: "20971520"
  restartPolicy: OnFailure
status: {}
