version: "3.0"
services: 
  app:
    build: .
    image: project-1:latest
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 50M
        reservations:
          cpus: '1'
          memory: 20M
    ports:
      - "8080:8080"
